### PR TITLE
#TODO: Change brush color if checkbox is activated

### PR DESCRIPTION
**Pull request by ChineseNorris**

### CODE REVIEW

**Comment by ChineseNorris** [comment]
Need to do the part where you want to change from one brush to another (White where inpaint is added to mask and black is removed from mask).

Github is a nightmare

**Comment by ChineseNorris** [comment]
@mashb1t

**Comment by mashb1t** [comment]
Will check this feature tomorrow, thanks!

**Comment by mashb1t** [comment]
@ChineseNorris 
AssqAJR8ib5WmCNGOU

Sorry, today!

**Comment by mashb1t** [comment]
@ChineseNorris sadly switching the color isn't that easy, we'd have to use a color picker (not only single color mask), then hide it using CSS and switch color with JS when activating the checkbox.
I'm sadly occupied with a lot of other things, maybe you're able to implement this, would highly appreciate it.
Thanks!

**Review by mashb1t — CHANGES_REQUESTED** [review]
@ChineseNorris sadly switching the color isn't that easy, we'd have to use a color picker (not only single color mask), then hide it using CSS and switch color with JS when activating the checkbox.
I'm sadly occupied with a lot of other things, maybe you're able to implement this, would highly appreciate it.
Thanks!

**Comment by ChineseNorris** [comment]
> @ChineseNorris sadly switching the color isn't that easy, we'd have to use a color picker (not only single color mask), then hide it using CSS and switch color with JS when activating the checkbox. I'm sadly occupied with a lot of other things, maybe you're able to implement this, would highly appreciate it. Thanks!

Ok I'll try my best to make it work, did you check the functionality at least? If it's okay I can begin to work on making it "prettier" @mashb1t

**Pull request closed without merging**
